spring:
  application:
    name: HiringAssignment

  datasource:
    url: jdbc:sqlite:./webhook.db
    driver-class-name: org.sqlite.JDBC

  sql:
    init:
      mode: always
      platform: sqlite

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true